'use client';

/**
 * Cinematic factory walkthrough. Five sticky stages, each backed by a Seedance
 * 2.0 video, scroll-tied. As the user scrolls past each section the matching
 * video plays + the copy crossfades in. Final stage has the conversion CTA.
 *
 * Sources: public/assets/factory/stage-{1..5}.mp4
 * Posters: public/assets/factory/stage-{1..5}-poster.jpg (auto-generated by stitch)
 *
 * Design: full-bleed video on left half (mobile: top), copy + CTA on right
 * half (mobile: below). One stage = 100vh on desktop, snap-y scroll. The video
 * loops while a stage is active; pauses when scrolled past.
 */

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { motion, useScroll, useTransform } from 'framer-motion';
import { ArrowRight, Sparkles } from 'lucide-react';

interface Stage {
  id: string;
  num: string;
  title: string;
  copy: string;
  video: string;
  poster?: string;
  cta?: { label: string; href: string };
}

const STAGES: Stage[] = [
  {
    id: 'receive',
    num: '01',
    title: 'you type one prompt.',
    copy: 'no kanban. no ticketing. you say what you want. brocco picks it up.',
    video: '/assets/factory/stage-1.mp4',
    poster: '/assets/factory/stage-1-poster.jpg',
  },
  {
    id: 'dispatch',
    num: '02',
    title: 'your supervisor dispatches the team.',
    copy: 'sully reads the prompt. nine specialists pick up nine parallel tracks before you finish your sentence.',
    video: '/assets/factory/stage-2.mp4',
    poster: '/assets/factory/stage-2-poster.jpg',
  },
  {
    id: 'execute',
    num: '03',
    title: 'nine offices light up at the same time.',
    copy: 'reggie pulls sources. penny stacks the plan. cody pushes code. daisy paints the deck. they run in parallel, not in a chat.',
    video: '/assets/factory/stage-3.mp4',
    poster: '/assets/factory/stage-3-poster.jpg',
  },
  {
    id: 'deliver',
    num: '04',
    title: 'outputs land in your dashboard.',
    copy: 'a grid of nine cards fills with green checks. each one opens to a finished artifact. ship it, edit it, or hand it back.',
    video: '/assets/factory/stage-4.mp4',
    poster: '/assets/factory/stage-4-poster.jpg',
  },
  {
    id: 'ship',
    num: '05',
    title: 'you sip coffee. you ship.',
    copy: 'one prompt, nine artifacts, twenty seconds. then you go again. that is the loop.',
    video: '/assets/factory/stage-5.mp4',
    poster: '/assets/factory/stage-5-poster.jpg',
    cta: { label: 'start your trial . $49/mo', href: '/checkout/solo' },
  },
];

function StageBlock({ stage, index }: { stage: Stage; index: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [inView, setInView] = useState(false);

  useEffect(() => {
    if (!ref.current) return;
    const obs = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            setInView(true);
            videoRef.current?.play().catch(() => {});
          } else {
            setInView(false);
            videoRef.current?.pause();
          }
        }
      },
      { threshold: 0.55 },
    );
    obs.observe(ref.current);
    return () => obs.disconnect();
  }, []);

  // Per-stage scroll progress drives copy entrance + parallax
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ['start end', 'end start'],
  });
  const copyY = useTransform(scrollYProgress, [0, 0.5, 1], [40, 0, -40]);
  const copyOpacity = useTransform(scrollYProgress, [0, 0.3, 0.7, 1], [0, 1, 1, 0]);
  const videoScale = useTransform(scrollYProgress, [0, 0.5, 1], [1.05, 1, 1.05]);

  return (
    <section
      ref={ref}
      id={`factory-${stage.id}`}
      className="relative min-h-screen w-full overflow-hidden bg-[#06080f]"
    >
      <div className="container-x relative grid min-h-screen grid-cols-1 items-center gap-8 py-20 md:grid-cols-2 md:gap-12 md:py-32">
        {/* Video panel */}
        <motion.div
          className={[
            'relative aspect-[9/16] w-full overflow-hidden rounded-[28px] border border-white/10 bg-[#06080f] shadow-[0_30px_120px_-30px_rgba(0,0,0,0.8)]',
            index % 2 === 0 ? 'md:order-1' : 'md:order-2',
          ].join(' ')}
          style={{ scale: videoScale }}
        >
          {/* Dark placeholder so the panel is never white before the poster /
              first video frame paints (fixes the white-flash on load + any
              missing-poster 404 on deploy). */}
          <div aria-hidden className="absolute inset-0 bg-[#06080f]" />
          <video
            ref={videoRef}
            className="absolute inset-0 h-full w-full bg-[#06080f] object-cover"
            src={stage.video}
            poster={stage.poster}
            muted
            loop
            playsInline
            preload="metadata"
          />
          {/* Vignette + brand grade */}
          <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_45%,transparent_0%,rgba(0,0,0,0.45)_85%)]" />
          {/* Bottom caption strip */}
          <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/75 via-black/30 to-transparent p-4 pt-10">
            <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.18em] text-white/70">
              <span className="inline-block h-1.5 w-1.5 rounded-full bg-brand" />
              stage {stage.num} · the brocco factory
            </div>
          </div>
        </motion.div>

        {/* Copy panel */}
        <motion.div
          className={[
            'relative',
            index % 2 === 0 ? 'md:order-2' : 'md:order-1',
          ].join(' ')}
          style={{ y: copyY, opacity: copyOpacity }}
        >
          <div className="flex items-center gap-3 text-[11px] uppercase tracking-[0.22em] text-ink-faint">
            <span className="font-mono text-brand">{stage.num}</span>
            <span className="h-px flex-1 bg-gradient-to-r from-white/15 to-transparent" />
          </div>
          <h2 className="mt-6 text-display-lg lowercase">
            <span className="text-grad">{stage.title}</span>
          </h2>
          <p className="mt-5 max-w-md text-[17px] leading-relaxed text-ink-dim">
            {stage.copy}
          </p>
          {stage.cta && (
            <div className="mt-8 flex flex-col items-start gap-3 sm:flex-row sm:items-center">
              <Link
                href={stage.cta.href}
                className="group inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-brand to-cyan px-6 py-3.5 text-[15px] font-semibold text-white shadow-glow2 transition-all hover:shadow-glow"
              >
                <Sparkles className="h-4 w-4" />
                <span>{stage.cta.label}</span>
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
              </Link>
              <span className="text-[12.5px] text-ink-faint">7-day free trial. cancel anytime.</span>
            </div>
          )}
        </motion.div>
      </div>

      {/* Stage divider */}
      {index < STAGES.length - 1 && (
        <div className="pointer-events-none absolute bottom-0 left-1/2 h-px w-3/4 -translate-x-1/2 bg-gradient-to-r from-transparent via-white/10 to-transparent" />
      )}
    </section>
  );
}

export function FactoryWalkthrough() {
  return (
    <div className="relative w-full bg-[#06080f]">
      {/* Intro */}
      <section className="relative flex min-h-[55vh] items-end pb-16 md:items-center md:pb-0">
        <div className="container-x relative">
          <div className="pill mb-5">the factory</div>
          <h2 className="text-display-lg lowercase">
            <span className="text-grad">walk through</span>{' '}
            <span className="text-grad-brand">the brocco factory.</span>
          </h2>
          <p className="mt-5 max-w-xl text-[17px] leading-relaxed text-ink-dim">
            five stages. one prompt in, nine outputs out. scroll to see it happen.
          </p>
        </div>
      </section>

      {STAGES.map((stage, i) => (
        <StageBlock key={stage.id} stage={stage} index={i} />
      ))}
    </div>
  );
}
